// generated by insrcdata version 0.3.0
import Foundation

public struct HelloWorld : Hashable {
        var cstruct : UnsafePointer<hello_world_t>
    
    init(cstruct: UnsafePointer<hello_world_t>){
        self.cstruct = cstruct
    }
    init(index:Int){
        cstruct = HELLO_WORLD_TABLE_PTR()+index
    }
    var sentence: String { String(cString:  hello_world_sentence(cstruct)) }

} // struct HelloWorld



