// generated by insrcdata version 0.1.0

#![allow(dead_code)]
#![allow(unused_variables)]
use std::ops::Deref;
pub struct Region {
    name_ : &'static str,
    code_ : u8,
}
impl PartialEq<Self> for Region {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self, other)
    }
}
impl Eq for Region {}
impl std::hash::Hash for Region {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        region::index_of(self).hash(state);
    }
}

impl Region {
    pub fn name(&self) -> &'static str { self.name_ }
    pub fn code(&self) -> u8 { self.code_ }

    pub fn subregions(&self) -> SubregionIter {
        let cons = region::index_of(self) as u8;

        // bissect left
        let mut lo = 0;
        let mut hi = subregion::REGION_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if cons > subregion::TABLE[subregion::REGION_INDEX[mid] as usize].region_ {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        let start = lo;

        // bissect-right
        hi = subregion::REGION_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if cons < subregion::TABLE[subregion::REGION_INDEX[mid] as usize].region_  {
                hi = mid;
            } else {
                lo = mid + 1;
            }
        }

        subregion::IndexIter {
            indexes: Box::new(subregion::REGION_INDEX[start..lo].iter()),
        }
    }
}

mod region {

pub fn index_of(fic:&super::Region) -> usize {
    ((fic  as *const _ as usize) - (&TABLE[0]  as *const _ as usize)) / std::mem::size_of::<super::Region>()
}
pub struct IndexIter {
    pub indexes : Box<dyn Iterator<Item=&'static u8>>,
}

impl Iterator for IndexIter {
    type Item = & 'static super::Region;

    fn next(&mut self) -> Option<&'static super::Region> {
        let idx = self.indexes.next();
        match idx {
            Some(v) => Some(&TABLE[*v as usize]),
            None => None,
        }
    }
}


const fn r(name:&'static str, code:u8, ) -> super::Region {
    super::Region{name_:name, code_:code, }
}

pub static TABLE : [ super::Region ; 5 ] = [
   {r("Asia", 142, )},
   {r("Europe", 150, )},
   {r("Africa", 2, )},
   {r("Oceania", 9, )},
   {r("Americas", 19, )},
];

} // mod region

pub use region::IndexIter as RegionIter;
pub struct Subregion {
    name_ : &'static str,
    code_ : u16,
    region_ : u8,
}
impl PartialEq<Self> for Subregion {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self, other)
    }
}
impl Eq for Subregion {}
impl std::hash::Hash for Subregion {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        subregion::index_of(self).hash(state);
    }
}

impl Subregion {
    pub fn name(&self) -> &'static str { self.name_ }
    pub fn code(&self) -> u16 { self.code_ }
    pub fn region(&self) -> &'static Region { &region::TABLE[self.region_ as usize]}

    pub fn countries(&self) -> CountryIter {
        let cons = subregion::index_of(self) as u8 + 1;

        // bissect left
        let mut lo = 0;
        let mut hi = country::SUBREGION_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if cons > country::TABLE[country::SUBREGION_INDEX[mid] as usize].subregion_ {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        let start = lo;

        // bissect-right
        hi = country::SUBREGION_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if cons < country::TABLE[country::SUBREGION_INDEX[mid] as usize].subregion_  {
                hi = mid;
            } else {
                lo = mid + 1;
            }
        }

        country::IndexIter {
            indexes: Box::new(country::SUBREGION_INDEX[start..lo].iter()),
        }
    }
}

mod subregion {

pub fn index_of(fic:&super::Subregion) -> usize {
    ((fic  as *const _ as usize) - (&TABLE[0]  as *const _ as usize)) / std::mem::size_of::<super::Subregion>()
}
pub struct IndexIter {
    pub indexes : Box<dyn Iterator<Item=&'static u8>>,
}

impl Iterator for IndexIter {
    type Item = & 'static super::Subregion;

    fn next(&mut self) -> Option<&'static super::Subregion> {
        let idx = self.indexes.next();
        match idx {
            Some(v) => Some(&TABLE[*v as usize]),
            None => None,
        }
    }
}


const fn r(name:&'static str, code:u16, region:u8, ) -> super::Subregion {
    super::Subregion{name_:name, code_:code, region_:region, }
}

pub static TABLE : [ super::Subregion ; 17 ] = [
   {r("Southern Asia", 34, 0, )},
   {r("Northern Europe", 154, 1, )},
   {r("Southern Europe", 39, 1, )},
   {r("Northern Africa", 15, 2, )},
   {r("Polynesia", 61, 3, )},
   {r("Sub-Saharan Africa", 202, 2, )},
   {r("Latin America and the Caribbean", 419, 4, )},
   {r("Western Asia", 145, 0, )},
   {r("Australia and New Zealand", 53, 3, )},
   {r("Western Europe", 155, 1, )},
   {r("Eastern Europe", 151, 1, )},
   {r("Northern America", 21, 4, )},
   {r("South-eastern Asia", 35, 0, )},
   {r("Eastern Asia", 30, 0, )},
   {r("Melanesia", 54, 3, )},
   {r("Micronesia", 57, 3, )},
   {r("Central Asia", 143, 0, )},
];
pub static REGION_INDEX : [ u8 ; 17 ] = [
     0,  7, 12, 13, 16,  1,  2,  9, 10,  3,  5,  4,  8, 14, 15,  6, 11, 
];

} // mod subregion

pub use subregion::IndexIter as SubregionIter;
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Countries {
    Antarctica = 8,
    Belgium = 21,
}
impl Deref for Countries {
    type Target =  Country;
    fn deref(&self) -> &'static Country {
        &country::TABLE[*self as usize]
    }
}
impl PartialEq<&Country> for Countries {
    fn eq(&self, other: &&Country) -> bool {
        std::ptr::eq(self as &Country, *other)
    }
}

pub struct Country {
    name_ : &'static str,
    alpha2_ : &'static str,
    alpha3_ : &'static str,
    code_ : u16,
    subregion_ : u8,
}
impl PartialEq<Self> for Country {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self, other)
    }
}
impl Eq for Country {}
impl std::hash::Hash for Country {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        country::index_of(self).hash(state);
    }
}

impl Country {
    pub fn name(&self) -> &'static str { self.name_ }
    pub fn alpha2(&self) -> &'static str { self.alpha2_ }
    pub fn alpha3(&self) -> &'static str { self.alpha3_ }

    pub fn alpha3_range(start:& str, stop:& str) -> country::IndexIter {
        let mut lo = 0;
        let mut hi = country::ALPHA3_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if start > country::TABLE[country::ALPHA3_INDEX[mid] as usize].alpha3_ {
                 lo = mid + 1;
            } else {
                 hi = mid;
            }
        }

        let begin = lo;
        hi = country::ALPHA3_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if stop < country::TABLE[country::ALPHA3_INDEX[mid] as usize].alpha3_ {
                hi = mid;
            } else {
                lo = mid + 1;
            }
        }
        country::IndexIter {
            indexes: Box::new(country::ALPHA3_INDEX[begin..lo].iter()),
        }
    }
    pub fn code(&self) -> u16 { self.code_ }

    pub fn code_range(start:u16, stop:u16) -> country::IndexIter {
        let mut lo = 0;
        let mut hi = country::CODE_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if start > country::TABLE[country::CODE_INDEX[mid] as usize].code_ {
                 lo = mid + 1;
            } else {
                 hi = mid;
            }
        }

        let begin = lo;
        hi = country::CODE_INDEX.len();
        while lo < hi {
            let mid = (lo + hi) / 2;
            if stop < country::TABLE[country::CODE_INDEX[mid] as usize].code_ {
                hi = mid;
            } else {
                lo = mid + 1;
            }
        }
        country::IndexIter {
            indexes: Box::new(country::CODE_INDEX[begin..lo].iter()),
        }
    }
    pub fn subregion(&self) -> Option<&'static Subregion> {
        let index = self.subregion_;
        if index==0 { None } else { Some(&subregion::TABLE[index as usize -1]) }
    }
    pub fn array() -> &'static [Country; 249] { &country::TABLE }
    pub fn as_index(&self) -> usize { country::index_of(self) }
}

mod country {

pub fn index_of(fic:&super::Country) -> usize {
    ((fic  as *const _ as usize) - (&TABLE[0]  as *const _ as usize)) / std::mem::size_of::<super::Country>()
}
pub struct IndexIter {
    pub indexes : Box<dyn Iterator<Item=&'static u8>>,
}

impl Iterator for IndexIter {
    type Item = & 'static super::Country;

    fn next(&mut self) -> Option<&'static super::Country> {
        let idx = self.indexes.next();
        match idx {
            Some(v) => Some(&TABLE[*v as usize]),
            None => None,
        }
    }
}


const fn r(name:&'static str, alpha2:&'static str, alpha3:&'static str, code:u16, subregion:u8, ) -> super::Country {
    super::Country{name_:name, alpha2_:alpha2, alpha3_:alpha3, code_:code, subregion_:subregion, }
}

pub static TABLE : [ super::Country ; 249 ] = [
   {r("Afghanistan", "AF", "AFG", 4, 1, )},
   {r("Åland Islands", "AX", "ALA", 248, 2, )},
   {r("Albania", "AL", "ALB", 8, 3, )},
   {r("Algeria", "DZ", "DZA", 12, 4, )},
   {r("American Samoa", "AS", "ASM", 16, 5, )},
   {r("Andorra", "AD", "AND", 20, 3, )},
   {r("Angola", "AO", "AGO", 24, 6, )},
   {r("Anguilla", "AI", "AIA", 660, 7, )},
   {r("Antarctica", "AQ", "ATA", 10, 0, )},
   {r("Antigua and Barbuda", "AG", "ATG", 28, 7, )},
   {r("Argentina", "AR", "ARG", 32, 7, )},
   {r("Armenia", "AM", "ARM", 51, 8, )},
   {r("Aruba", "AW", "ABW", 533, 7, )},
   {r("Australia", "AU", "AUS", 36, 9, )},
   {r("Austria", "AT", "AUT", 40, 10, )},
   {r("Azerbaijan", "AZ", "AZE", 31, 8, )},
   {r("Bahamas", "BS", "BHS", 44, 7, )},
   {r("Bahrain", "BH", "BHR", 48, 8, )},
   {r("Bangladesh", "BD", "BGD", 50, 1, )},
   {r("Barbados", "BB", "BRB", 52, 7, )},
   {r("Belarus", "BY", "BLR", 112, 11, )},
   {r("Belgium", "BE", "BEL", 56, 10, )},
   {r("Belize", "BZ", "BLZ", 84, 7, )},
   {r("Benin", "BJ", "BEN", 204, 6, )},
   {r("Bermuda", "BM", "BMU", 60, 12, )},
   {r("Bhutan", "BT", "BTN", 64, 1, )},
   {r("Bolivia (Plurinational State of)", "BO", "BOL", 68, 7, )},
   {r("Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535, 7, )},
   {r("Bosnia and Herzegovina", "BA", "BIH", 70, 3, )},
   {r("Botswana", "BW", "BWA", 72, 6, )},
   {r("Bouvet Island", "BV", "BVT", 74, 7, )},
   {r("Brazil", "BR", "BRA", 76, 7, )},
   {r("British Indian Ocean Territory", "IO", "IOT", 86, 6, )},
   {r("Brunei Darussalam", "BN", "BRN", 96, 13, )},
   {r("Bulgaria", "BG", "BGR", 100, 11, )},
   {r("Burkina Faso", "BF", "BFA", 854, 6, )},
   {r("Burundi", "BI", "BDI", 108, 6, )},
   {r("Cabo Verde", "CV", "CPV", 132, 6, )},
   {r("Cambodia", "KH", "KHM", 116, 13, )},
   {r("Cameroon", "CM", "CMR", 120, 6, )},
   {r("Canada", "CA", "CAN", 124, 12, )},
   {r("Cayman Islands", "KY", "CYM", 136, 7, )},
   {r("Central African Republic", "CF", "CAF", 140, 6, )},
   {r("Chad", "TD", "TCD", 148, 6, )},
   {r("Chile", "CL", "CHL", 152, 7, )},
   {r("China", "CN", "CHN", 156, 14, )},
   {r("Christmas Island", "CX", "CXR", 162, 9, )},
   {r("Cocos (Keeling) Islands", "CC", "CCK", 166, 9, )},
   {r("Colombia", "CO", "COL", 170, 7, )},
   {r("Comoros", "KM", "COM", 174, 6, )},
   {r("Congo", "CG", "COG", 178, 6, )},
   {r("Congo, Democratic Republic of the", "CD", "COD", 180, 6, )},
   {r("Cook Islands", "CK", "COK", 184, 5, )},
   {r("Costa Rica", "CR", "CRI", 188, 7, )},
   {r("Côte d'Ivoire", "CI", "CIV", 384, 6, )},
   {r("Croatia", "HR", "HRV", 191, 3, )},
   {r("Cuba", "CU", "CUB", 192, 7, )},
   {r("Curaçao", "CW", "CUW", 531, 7, )},
   {r("Cyprus", "CY", "CYP", 196, 8, )},
   {r("Czechia", "CZ", "CZE", 203, 11, )},
   {r("Denmark", "DK", "DNK", 208, 2, )},
   {r("Djibouti", "DJ", "DJI", 262, 6, )},
   {r("Dominica", "DM", "DMA", 212, 7, )},
   {r("Dominican Republic", "DO", "DOM", 214, 7, )},
   {r("Ecuador", "EC", "ECU", 218, 7, )},
   {r("Egypt", "EG", "EGY", 818, 4, )},
   {r("El Salvador", "SV", "SLV", 222, 7, )},
   {r("Equatorial Guinea", "GQ", "GNQ", 226, 6, )},
   {r("Eritrea", "ER", "ERI", 232, 6, )},
   {r("Estonia", "EE", "EST", 233, 2, )},
   {r("Eswatini", "SZ", "SWZ", 748, 6, )},
   {r("Ethiopia", "ET", "ETH", 231, 6, )},
   {r("Falkland Islands (Malvinas)", "FK", "FLK", 238, 7, )},
   {r("Faroe Islands", "FO", "FRO", 234, 2, )},
   {r("Fiji", "FJ", "FJI", 242, 15, )},
   {r("Finland", "FI", "FIN", 246, 2, )},
   {r("France", "FR", "FRA", 250, 10, )},
   {r("French Guiana", "GF", "GUF", 254, 7, )},
   {r("French Polynesia", "PF", "PYF", 258, 5, )},
   {r("French Southern Territories", "TF", "ATF", 260, 6, )},
   {r("Gabon", "GA", "GAB", 266, 6, )},
   {r("Gambia", "GM", "GMB", 270, 6, )},
   {r("Georgia", "GE", "GEO", 268, 8, )},
   {r("Germany", "DE", "DEU", 276, 10, )},
   {r("Ghana", "GH", "GHA", 288, 6, )},
   {r("Gibraltar", "GI", "GIB", 292, 3, )},
   {r("Greece", "GR", "GRC", 300, 3, )},
   {r("Greenland", "GL", "GRL", 304, 12, )},
   {r("Grenada", "GD", "GRD", 308, 7, )},
   {r("Guadeloupe", "GP", "GLP", 312, 7, )},
   {r("Guam", "GU", "GUM", 316, 16, )},
   {r("Guatemala", "GT", "GTM", 320, 7, )},
   {r("Guernsey", "GG", "GGY", 831, 2, )},
   {r("Guinea", "GN", "GIN", 324, 6, )},
   {r("Guinea-Bissau", "GW", "GNB", 624, 6, )},
   {r("Guyana", "GY", "GUY", 328, 7, )},
   {r("Haiti", "HT", "HTI", 332, 7, )},
   {r("Heard Island and McDonald Islands", "HM", "HMD", 334, 9, )},
   {r("Holy See", "VA", "VAT", 336, 3, )},
   {r("Honduras", "HN", "HND", 340, 7, )},
   {r("Hong Kong", "HK", "HKG", 344, 14, )},
   {r("Hungary", "HU", "HUN", 348, 11, )},
   {r("Iceland", "IS", "ISL", 352, 2, )},
   {r("India", "IN", "IND", 356, 1, )},
   {r("Indonesia", "ID", "IDN", 360, 13, )},
   {r("Iran (Islamic Republic of)", "IR", "IRN", 364, 1, )},
   {r("Iraq", "IQ", "IRQ", 368, 8, )},
   {r("Ireland", "IE", "IRL", 372, 2, )},
   {r("Isle of Man", "IM", "IMN", 833, 2, )},
   {r("Israel", "IL", "ISR", 376, 8, )},
   {r("Italy", "IT", "ITA", 380, 3, )},
   {r("Jamaica", "JM", "JAM", 388, 7, )},
   {r("Japan", "JP", "JPN", 392, 14, )},
   {r("Jersey", "JE", "JEY", 832, 2, )},
   {r("Jordan", "JO", "JOR", 400, 8, )},
   {r("Kazakhstan", "KZ", "KAZ", 398, 17, )},
   {r("Kenya", "KE", "KEN", 404, 6, )},
   {r("Kiribati", "KI", "KIR", 296, 16, )},
   {r("Korea (Democratic People's Republic of)", "KP", "PRK", 408, 14, )},
   {r("Korea, Republic of", "KR", "KOR", 410, 14, )},
   {r("Kuwait", "KW", "KWT", 414, 8, )},
   {r("Kyrgyzstan", "KG", "KGZ", 417, 17, )},
   {r("Lao People's Democratic Republic", "LA", "LAO", 418, 13, )},
   {r("Latvia", "LV", "LVA", 428, 2, )},
   {r("Lebanon", "LB", "LBN", 422, 8, )},
   {r("Lesotho", "LS", "LSO", 426, 6, )},
   {r("Liberia", "LR", "LBR", 430, 6, )},
   {r("Libya", "LY", "LBY", 434, 4, )},
   {r("Liechtenstein", "LI", "LIE", 438, 10, )},
   {r("Lithuania", "LT", "LTU", 440, 2, )},
   {r("Luxembourg", "LU", "LUX", 442, 10, )},
   {r("Macao", "MO", "MAC", 446, 14, )},
   {r("Madagascar", "MG", "MDG", 450, 6, )},
   {r("Malawi", "MW", "MWI", 454, 6, )},
   {r("Malaysia", "MY", "MYS", 458, 13, )},
   {r("Maldives", "MV", "MDV", 462, 1, )},
   {r("Mali", "ML", "MLI", 466, 6, )},
   {r("Malta", "MT", "MLT", 470, 3, )},
   {r("Marshall Islands", "MH", "MHL", 584, 16, )},
   {r("Martinique", "MQ", "MTQ", 474, 7, )},
   {r("Mauritania", "MR", "MRT", 478, 6, )},
   {r("Mauritius", "MU", "MUS", 480, 6, )},
   {r("Mayotte", "YT", "MYT", 175, 6, )},
   {r("Mexico", "MX", "MEX", 484, 7, )},
   {r("Micronesia (Federated States of)", "FM", "FSM", 583, 16, )},
   {r("Moldova, Republic of", "MD", "MDA", 498, 11, )},
   {r("Monaco", "MC", "MCO", 492, 10, )},
   {r("Mongolia", "MN", "MNG", 496, 14, )},
   {r("Montenegro", "ME", "MNE", 499, 3, )},
   {r("Montserrat", "MS", "MSR", 500, 7, )},
   {r("Morocco", "MA", "MAR", 504, 4, )},
   {r("Mozambique", "MZ", "MOZ", 508, 6, )},
   {r("Myanmar", "MM", "MMR", 104, 13, )},
   {r("Namibia", "NA", "NAM", 516, 6, )},
   {r("Nauru", "NR", "NRU", 520, 16, )},
   {r("Nepal", "NP", "NPL", 524, 1, )},
   {r("Netherlands", "NL", "NLD", 528, 10, )},
   {r("New Caledonia", "NC", "NCL", 540, 15, )},
   {r("New Zealand", "NZ", "NZL", 554, 9, )},
   {r("Nicaragua", "NI", "NIC", 558, 7, )},
   {r("Niger", "NE", "NER", 562, 6, )},
   {r("Nigeria", "NG", "NGA", 566, 6, )},
   {r("Niue", "NU", "NIU", 570, 5, )},
   {r("Norfolk Island", "NF", "NFK", 574, 9, )},
   {r("North Macedonia", "MK", "MKD", 807, 3, )},
   {r("Northern Mariana Islands", "MP", "MNP", 580, 16, )},
   {r("Norway", "NO", "NOR", 578, 2, )},
   {r("Oman", "OM", "OMN", 512, 8, )},
   {r("Pakistan", "PK", "PAK", 586, 1, )},
   {r("Palau", "PW", "PLW", 585, 16, )},
   {r("Palestine, State of", "PS", "PSE", 275, 8, )},
   {r("Panama", "PA", "PAN", 591, 7, )},
   {r("Papua New Guinea", "PG", "PNG", 598, 15, )},
   {r("Paraguay", "PY", "PRY", 600, 7, )},
   {r("Peru", "PE", "PER", 604, 7, )},
   {r("Philippines", "PH", "PHL", 608, 13, )},
   {r("Pitcairn", "PN", "PCN", 612, 5, )},
   {r("Poland", "PL", "POL", 616, 11, )},
   {r("Portugal", "PT", "PRT", 620, 3, )},
   {r("Puerto Rico", "PR", "PRI", 630, 7, )},
   {r("Qatar", "QA", "QAT", 634, 8, )},
   {r("Réunion", "RE", "REU", 638, 6, )},
   {r("Romania", "RO", "ROU", 642, 11, )},
   {r("Russian Federation", "RU", "RUS", 643, 11, )},
   {r("Rwanda", "RW", "RWA", 646, 6, )},
   {r("Saint Barthélemy", "BL", "BLM", 652, 7, )},
   {r("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654, 6, )},
   {r("Saint Kitts and Nevis", "KN", "KNA", 659, 7, )},
   {r("Saint Lucia", "LC", "LCA", 662, 7, )},
   {r("Saint Martin (French part)", "MF", "MAF", 663, 7, )},
   {r("Saint Pierre and Miquelon", "PM", "SPM", 666, 12, )},
   {r("Saint Vincent and the Grenadines", "VC", "VCT", 670, 7, )},
   {r("Samoa", "WS", "WSM", 882, 5, )},
   {r("San Marino", "SM", "SMR", 674, 3, )},
   {r("Sao Tome and Principe", "ST", "STP", 678, 6, )},
   {r("Saudi Arabia", "SA", "SAU", 682, 8, )},
   {r("Senegal", "SN", "SEN", 686, 6, )},
   {r("Serbia", "RS", "SRB", 688, 3, )},
   {r("Seychelles", "SC", "SYC", 690, 6, )},
   {r("Sierra Leone", "SL", "SLE", 694, 6, )},
   {r("Singapore", "SG", "SGP", 702, 13, )},
   {r("Sint Maarten (Dutch part)", "SX", "SXM", 534, 7, )},
   {r("Slovakia", "SK", "SVK", 703, 11, )},
   {r("Slovenia", "SI", "SVN", 705, 3, )},
   {r("Solomon Islands", "SB", "SLB", 90, 15, )},
   {r("Somalia", "SO", "SOM", 706, 6, )},
   {r("South Africa", "ZA", "ZAF", 710, 6, )},
   {r("South Georgia and the South Sandwich Islands", "GS", "SGS", 239, 7, )},
   {r("South Sudan", "SS", "SSD", 728, 6, )},
   {r("Spain", "ES", "ESP", 724, 3, )},
   {r("Sri Lanka", "LK", "LKA", 144, 1, )},
   {r("Sudan", "SD", "SDN", 729, 4, )},
   {r("Suriname", "SR", "SUR", 740, 7, )},
   {r("Svalbard and Jan Mayen", "SJ", "SJM", 744, 2, )},
   {r("Sweden", "SE", "SWE", 752, 2, )},
   {r("Switzerland", "CH", "CHE", 756, 10, )},
   {r("Syrian Arab Republic", "SY", "SYR", 760, 8, )},
   {r("Taiwan, Province of China", "TW", "TWN", 158, 14, )},
   {r("Tajikistan", "TJ", "TJK", 762, 17, )},
   {r("Tanzania, United Republic of", "TZ", "TZA", 834, 6, )},
   {r("Thailand", "TH", "THA", 764, 13, )},
   {r("Timor-Leste", "TL", "TLS", 626, 13, )},
   {r("Togo", "TG", "TGO", 768, 6, )},
   {r("Tokelau", "TK", "TKL", 772, 5, )},
   {r("Tonga", "TO", "TON", 776, 5, )},
   {r("Trinidad and Tobago", "TT", "TTO", 780, 7, )},
   {r("Tunisia", "TN", "TUN", 788, 4, )},
   {r("Turkey", "TR", "TUR", 792, 8, )},
   {r("Turkmenistan", "TM", "TKM", 795, 17, )},
   {r("Turks and Caicos Islands", "TC", "TCA", 796, 7, )},
   {r("Tuvalu", "TV", "TUV", 798, 5, )},
   {r("Uganda", "UG", "UGA", 800, 6, )},
   {r("Ukraine", "UA", "UKR", 804, 11, )},
   {r("United Arab Emirates", "AE", "ARE", 784, 8, )},
   {r("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", 826, 2, )},
   {r("United States of America", "US", "USA", 840, 12, )},
   {r("United States Minor Outlying Islands", "UM", "UMI", 581, 16, )},
   {r("Uruguay", "UY", "URY", 858, 7, )},
   {r("Uzbekistan", "UZ", "UZB", 860, 17, )},
   {r("Vanuatu", "VU", "VUT", 548, 15, )},
   {r("Venezuela (Bolivarian Republic of)", "VE", "VEN", 862, 7, )},
   {r("Viet Nam", "VN", "VNM", 704, 13, )},
   {r("Virgin Islands (British)", "VG", "VGB", 92, 7, )},
   {r("Virgin Islands (U.S.)", "VI", "VIR", 850, 7, )},
   {r("Wallis and Futuna", "WF", "WLF", 876, 5, )},
   {r("Western Sahara", "EH", "ESH", 732, 4, )},
   {r("Yemen", "YE", "YEM", 887, 8, )},
   {r("Zambia", "ZM", "ZMB", 894, 6, )},
   {r("Zimbabwe", "ZW", "ZWE", 716, 6, )},
];
pub static ALPHA3_INDEX : [ u8 ; 249 ] = [
     12,   0,   6,   7,   1,   2,   5, 233,  10,  11,   4,   8,  79,   9,  13,  14,  15,  36,  21,  23, 
     27,  35,  18,  34,  17,  16,  28, 185,  20,  22,  24,  26,  31,  19,  33,  25,  30,  29,  42,  40, 
     47, 215,  44,  45,  54,  39,  51,  50,  52,  48,  49,  37,  53,  56,  57,  46,  41,  58,  59,  83, 
     61,  62,  60,  63,   3,  64,  65,  68, 245, 209,  69,  71,  75,  74,  72,  76,  73, 144,  80, 234, 
     82,  92,  84,  85,  93,  89,  81,  94,  67,  86,  88,  87,  91,  77,  90,  95, 100,  97,  99,  55, 
     96, 101, 104, 108, 103,  32, 107, 105, 106, 102, 109, 110, 111, 113, 114, 112, 115, 116, 121,  38, 
    117, 187, 119, 120, 122, 124, 126, 127, 188, 128, 210, 125, 129, 130, 123, 131, 189, 150, 146, 145, 
    132, 135, 143, 138, 164, 136, 137, 152, 148, 147, 165, 151, 140, 149, 139, 141, 133, 134, 142, 153, 
    157, 160, 163, 161, 159, 162, 156, 166, 155, 154, 158, 167, 168, 171, 176, 174, 175, 169, 172, 177, 
    179, 118, 178, 173, 170,  78, 180, 181, 182, 183, 184, 195, 211, 196, 200, 207, 186, 213, 204, 199, 
     66, 193, 205, 190, 197, 208, 194, 212, 202, 203, 214,  70, 201, 198, 216, 229,  43, 222, 220, 218, 
    223, 228, 221, 224, 225, 226, 227, 230, 217, 219, 231, 232, 236, 237, 235, 238,  98, 191, 240, 242, 
    243, 241, 239, 244, 192, 246, 206, 247, 248, 
];
pub static CODE_INDEX : [ u8 ; 249 ] = [
      0,   2,   8,   3,   4,   5,   6,   9,  15,  10,  13,  14,  16,  17,  18,  11,  19,  21,  24,  25, 
     26,  28,  29,  30,  31,  22,  32, 204, 242,  33,  34, 152,  36,  20,  38,  39,  40,  37,  41,  42, 
    210,  43,  44,  45, 217,  46,  47,  48,  49, 142,  50,  51,  52,  53,  55,  56,  58,  59,  23,  60, 
     62,  63,  64,  66,  67,  71,  68,  69,  73,  72, 207,  74,  75,   1,  76,  77,  78,  79,  61,  80, 
     82,  81, 170,  83,  84,  85, 117,  86,  87,  88,  89,  90,  91,  93,  95,  96,  97,  98,  99, 100, 
    101, 102, 103, 104, 105, 106, 107, 109, 110,  54, 111, 112, 115, 114, 116, 118, 119, 120, 121, 122, 
    124, 125, 123, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 139, 140, 141, 143, 146, 
    147, 145, 148, 149, 150, 151, 167, 153, 154, 155, 156,  57,  12, 201,  27, 157, 239, 158, 159, 160, 
    161, 162, 163, 166, 165, 236, 144, 138, 169, 168, 171, 172, 173, 174, 175, 176, 177, 178,  94, 221, 
    179, 180, 181, 182, 183, 184, 185, 186, 187,   7, 188, 189, 190, 191, 193, 194, 195, 196, 197, 198, 
    199, 200, 202, 241, 203, 205, 206, 248, 209, 208, 211, 245, 212, 213,  70, 214, 215, 216, 218, 220, 
    222, 223, 224, 225, 233, 226, 227, 228, 229, 230, 231, 232, 164,  65, 234,  92, 113, 108, 219, 235, 
    243,  35, 237, 238, 240, 244, 192, 246, 247, 
];
pub static SUBREGION_INDEX : [ u8 ; 248 ] = [
      0,  18,  25, 103, 105, 135, 155, 168, 210,   1,  60,  69,  73,  75,  92, 102, 107, 108, 113, 123, 
    129, 166, 213, 214, 234,   2,   5,  28,  55,  85,  86,  98, 110, 137, 148, 164, 178, 193, 197, 203, 
    209,   3,  65, 127, 150, 211, 226, 245,   4,  52,  78, 162, 176, 192, 223, 224, 230, 244,   6,  23, 
     29,  32,  35,  36,  37,  39,  42,  43,  49,  50,  51,  54,  61,  67,  68,  70,  71,  79,  80,  81, 
     84,  93,  94, 116, 125, 126, 132, 133, 136, 140, 141, 142, 151, 153, 160, 161, 181, 184, 186, 194, 
    196, 198, 199, 205, 206, 208, 219, 222, 231, 247, 248,   7,   9,  10,  12,  16,  19,  22,  26,  27, 
     30,  31,  41,  44,  48,  53,  56,  57,  62,  63,  64,  66,  72,  77,  88,  89,  91,  95,  96,  99, 
    111, 139, 143, 149, 159, 171, 173, 174, 179, 185, 187, 188, 189, 191, 201, 207, 212, 225, 229, 237, 
    240, 242, 243,  11,  15,  17,  58,  82, 106, 109, 114, 120, 124, 167, 170, 180, 195, 216, 227, 233, 
    246,  13,  46,  47,  97, 158, 163,  14,  21,  76,  83, 128, 130, 146, 156, 215,  20,  34,  59, 101, 
    145, 177, 182, 183, 202, 232,  24,  40,  87, 190, 235,  33,  38, 104, 122, 134, 152, 175, 200, 220, 
    221, 241,  45, 100, 112, 118, 119, 131, 147, 217,  74, 157, 172, 204, 239,  90, 117, 138, 144, 154, 
    165, 169, 236, 115, 121, 218, 228, 238, 
];

} // mod country

pub use country::IndexIter as CountryIter;
