// generated by insrcdata version 0.1.0

#![allow(dead_code)]
#![allow(unused_variables)]
pub struct HelloWorld {
    sentence_ : &'static str,
}
impl PartialEq<Self> for HelloWorld {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self, other)
    }
}
impl HelloWorld {
    pub fn sentence(&self) -> &'static str { self.sentence_ }
    pub fn array() -> &'static [HelloWorld; 2]  { &hello_world::TABLE }
}

mod hello_world {

const fn r(sentence:&'static str, ) -> super::HelloWorld {
    super::HelloWorld{sentence_:sentence, }
}

pub static TABLE : [ super::HelloWorld ; 2 ] = [
   {r("Hello", )},
   {r("World !", )},
];

} // mod hello_world

