// generated by insrcdata version 0.1.0

#ifndef INSRCDATA_INSRCDATA_H
#define INSRCDATA_INSRCDATA_H
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>



// ------    
typedef enum {
    LABELS_FOO = 0,
    LABELS_BAR = 1,
    LABELS_UPPER_CAMEL_CASE = 2,
    LABELS_LOWER_CAMEL_CASE = 3,
    LABELS_SNAKE_CASE = 4,
    LABELS_KEBAB_CASE = 5,
    LABELS_SHOUTY_SNAKE_CASE = 6,
    LABELS_TITLE_CASE = 7,
    LABELS_SHOUTY_KEBAB_CASE = 8,
    LABELS_TRAIN_CASE = 9,
} labels_t;

#endif //  INSRCDATA_H 
