// generated by insrcdata version 0.3.0
import Foundation

public struct Label : Hashable {
        var cstruct : UnsafePointer<label_t>
    
    init(cstruct: UnsafePointer<label_t>){
        self.cstruct = cstruct
    }
    init(ref:labels_t){
        cstruct = label_from_labels(ref)
    }
    var labels: labels_t { label_labels(cstruct) }
    init(index:Int){
        cstruct = LABEL_TABLE_PTR()+index
    }
    var title: String { String(cString:  label_title(cstruct)) }

} // struct Label



