// generated by insrcdata version 0.1.0

#![allow(dead_code)]
#![allow(unused_variables)]
#[derive(Clone, Copy)]
pub enum Labels {
    Foo = 0,
    Bar = 1,
    UpperCamelCase = 2,
    LowerCamelCase = 3,
    SnakeCase = 4,
    KebabCase = 5,
    ShoutySnakeCase = 6,
    TitleCase = 7,
    ShoutyKebabCase = 8,
    TrainCase = 9,
}
