// generated by insrcdata version 0.1.0

#ifndef INSRCDATA_INSRCDATA_H
#define INSRCDATA_INSRCDATA_H
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct  {
    char* name_;
    uint8_t spouse_;
    uint8_t father_;
    uint8_t mother_;
} person_t;



// ------    
typedef enum {
    PERSONS_MARIE = 0,
    PERSONS_PIERRE = 1,
    PERSONS_IRENE = 2,
    PERSONS_FREDERIC = 3,
} persons_t;
const person_t* person_from_persons(persons_t label);
persons_t person_persons(const person_t *s);
            
static inline const char* person_name(const person_t* s) { return s->name_; }
extern const person_t* person_spouse(const person_t* s);
extern bool person_father(const person_t* s, const person_t** ptr);
extern bool person_mother(const person_t* s, const person_t** ptr);
#endif //  INSRCDATA_H 
