// generated by insrcdata version 0.1.0

#ifndef INSRCDATA_INSRCDATA_H
#define INSRCDATA_INSRCDATA_H
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct  {
    char* name_;
    uint8_t spouse_;
    uint8_t father_;
    uint8_t mother_;
} person_t;
static unsigned const PERSON_TABLE_COUNT = 4;
extern person_t PERSON_TABLE[PERSON_TABLE_COUNT];



// ------    
typedef enum {
    PERSONS_MARIE = 0,
    PERSONS_PIERRE = 1,
    PERSONS_IRENE = 2,
    PERSONS_FREDERIC = 3,
} persons_t;
static inline char* person_name(const person_t* s) { return s->name_; }
static inline person_t* person_spouse(const person_t* s) { return &PERSON_TABLE[s->spouse_];}
static inline bool person_father(const person_t* s, person_t** ptr)
{ 
    if( s->father_) {
        *ptr = &PERSON_TABLE[s->father_-1];
        return true;
    }
    return false;
}
static inline bool person_mother(const person_t* s, person_t** ptr)
{ 
    if( s->mother_) {
        *ptr = &PERSON_TABLE[s->mother_-1];
        return true;
    }
    return false;
}
#endif //  INSRCDATA_H 
